title: Ovidiu Suciu
github_username: socovidiu
name: Digital Portfolio
tagline: Software Developer · Full-Stack Enthusiast · Always up for a challenge
theme: null
baseurl: "/my-website"
url: "https://socovidiu.github.io"
plugins: 
  - jekyll-seo-tag
  # - jekyll-sitemap
collections:
  projects:
    output: true
