title: Ovidiu Suciu
github_username: socovidiu
name: Digital Portfolio
tagline: Full-Stack Developer & AI/LLM Integration Engineer
theme: null
baseurl: "/my-website"
url: "https://socovidiu.github.io"
plugins: 
  - jekyll-seo-tag
  # - jekyll-sitemap
collections:
  projects:
    output: true
